### ISSUE TITLE
Android app without ads have loer functionality than Free&Ad version

### ISSUE THREAD

**Issue by petakpa1** [Depicus/wake-on-lan-for-windows-3.1#1]
Hi,

I have just purchased the paid version (without ads) version in the Play webstore in the hope that in the paid version I will be able to rename my bookmarks.  Contrary to the screenshots shown in the play store there is no bookmark function in the paid version at all. Later I realized that the paid version was last updated back in 2012:(

Is there any chance that you will issue a fresh version of paid one too without ads but with bookmark and rename bookmark functions?

Sorry for contacting you here, but I do not use twitter and you have no other public contact at all.

Kind regards,
Peter

**Comment by Depicus** [comment]
Will dig out the code and see what I can do but I think the problem with updating the paid app was that I didn't have the cert I originally used to upload it. Give me a few days.

**Comment by Depicus** [comment]
Ok finally found the right signing key and uploaded a new version so currently in review and should be released soon.
